# Generated by Django 4.1 on 2024-01-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_user_country_user_phone_number_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profile_images'),
        ),
    ]
